import axios from "axios";
import dotenv from 'dotenv';
dotenv.config();

const API_URL = process.env.HUAWEI_LLM_ENDPOINT || 'https://pangu.ap-southeast-1.myhuaweicloud.com/api/v2/chat/completions';
const AUTH_TOKEN = process.env.LLM_API_KEY;

const DEFAULT_SYSTEM_MESSAGE = `
You are DEKAI, an AI-powered poultry health assistant for small-scale and indigenous farmers.
Your goal is to guide farmers in detecting poultry diseases early, monitoring farm conditions, and taking actionable steps to improve flock health.
Always speak directly to the farmer in a friendly, empathetic, and concise manner.
Provide clear, step-by-step advice based on symptoms, images, or environmental data.
Incorporate indigenous knowledge and safe veterinary practices where appropriate.
Focus on actionable instructions, preventive measures, and improving poultry welfare.
Avoid referring to yourself; address the farmer directly as "you".
`;

export async function chatbotResponse(userMessage, systemMessage = DEFAULT_SYSTEM_MESSAGE, options = {}) {
  try {
    const messages = [];

    if (systemMessage) {
      messages.push({ role: "system", content: systemMessage });
    }

    messages.push({ role: "user", content: userMessage });

    const payload = {
      model: "distill-llama-8b_46e6iu",
      messages: messages,
      stream: false,
      ...options, // max_tokens, temperature, top_p, etc.
    };

    // Remove empty or undefined options to avoid API issues
    Object.keys(payload).forEach(key => payload[key] === undefined && delete payload[key]);

    const config = {
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${AUTH_TOKEN}`,
      },
      timeout: 60000, // 60 seconds timeout
    };

    console.log(`🔍 Making request to: ${API_URL}`);
    console.log(`🔍 Using model: ${payload.model}`);

    const response = await axios.post(API_URL, payload, config);

    if (!response.data) throw new Error("Empty response from AI service");
    if (response.data.error) throw new Error(`AI Service Error: ${JSON.stringify(response.data.error)}`);

    const generatedText =
      response.data?.choices?.[0]?.message?.content ||
      response.data?.result?.response ||
      "No response generated by the AI model.";

    return generatedText.trim();
  } catch (error) {
    console.error("❌ Huawei AI Service Error:");

    if (error.response) {
      console.error("Status:", error.response.status);
      console.error("Headers:", error.response.headers);
      console.error("Data:", JSON.stringify(error.response.data, null, 2));

      if (error.response.data?.error?.code === 'PANGU.3254') {
        console.error("💡 Solution: The model may not be available in your region or may require specific activation.");
      }
    } else if (error.request) {
      console.error("No response received:", error.request);
    } else {
      console.error("Error message:", error.message);
    }

    throw new Error(`AI model request failed: ${error.message}`);
  }
}

// Test example
(async () => {
  try {
    console.log("🤖 Testing DEKAI AI Service...");

    const result = await chatbotResponse(
      "What should I do if my chickens have watery eyes and droopy posture?",
      undefined, // use default system instructions
      {
        max_tokens: 250,
        temperature: 0.7,
        top_p: 0.9
      }
    );

    console.log("✅ Model Output:", result);
  } catch (error) {
    console.error("❌ Error in chatbot call:", error.message);
  }
})();
