import axios from "axios";
import dotenv from 'dotenv';
dotenv.config();

const API_URL = process.env.HUAWEI_LLM_ENDPOINT || 'https://pangu.ap-southeast-1.myhuaweicloud.com/api/v2/chat/completions';
const AUTH_TOKEN = process.env.LLM_API_KEY;

const DEFAULT_SYSTEM_MESSAGE = `
You are DEKAI Assistant, a friendly AI helper for poultry farmers in Kenya and East Africa.

CRITICAL RULES:
1. **NO THINKING ALOUD**: Never start with "Okay", "Let me", "I should", or explain your thought process. Give the answer immediately.
2. **SUMMARIZE FIRST**: Give a brief 1-2 sentence summary answer first. Only provide details if the farmer asks follow-up questions.
3. **DIRECT & ACTIONABLE**: Tell farmers exactly what to do. Use commands like "Take photos", "Check sensors", "Isolate sick birds".
4. **ULTRA-CONCISE**: Maximum 2-3 short sentences for initial responses. Farmers are on mobile phones.
5. **BE INQUISITIVE**: If information is missing, ask ONE short clarifying question first.
6. **EXPAND ONLY WHEN ASKED**: Wait for the farmer to ask for more details before giving comprehensive information.

RESPONSE PATTERN:
- **First response**: 1-2 sentence summary + one actionable step
- **If farmer asks "tell me more" or "explain"**: Then provide additional details
- **If farmer asks specific follow-up**: Then focus only on that specific point

EXAMPLES OF GOOD RESPONSES:
- "Newcastle and Gumboro are most common. Take photos in the app for specific diagnosis."
- "Check your temperature sensor. Chicks need 32-35°C in first week."
- "Increase ventilation immediately. What's your ammonia reading?"
- "Isolate sick birds first. Then describe their symptoms for better advice."

BAD RESPONSES TO AVOID:
- "Okay, let me help you with that..." ❌
- Long lists and structured points in first response ❌
- Giving comprehensive details without being asked ❌

TONE: Direct, supportive, like giving urgent advice to a neighbor.
`;

export async function chatbotResponse(userMessage, systemMessage = DEFAULT_SYSTEM_MESSAGE, options = {}) {
  try {
    const messages = [];

    if (systemMessage) {
      messages.push({ role: "system", content: systemMessage });
    }

    messages.push({ role: "user", content: userMessage });

    const payload = {
      model: "distill-llama-8b_46e6iu",
      messages: messages,
      stream: false,
      ...options, // max_tokens, temperature, top_p, etc.
    };

    // Remove empty or undefined options to avoid API issues
    Object.keys(payload).forEach(key => payload[key] === undefined && delete payload[key]);

    const config = {
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${AUTH_TOKEN}`,
      },
      timeout: 60000, // 60 seconds timeout
    };

    console.log(`🔍 Making request to: ${API_URL}`);
    console.log(`🔍 Using model: ${payload.model}`);

    const response = await axios.post(API_URL, payload, config);

    if (!response.data) throw new Error("Empty response from AI service");
    if (response.data.error) throw new Error(`AI Service Error: ${JSON.stringify(response.data.error)}`);

    const generatedText =
      response.data?.choices?.[0]?.message?.content ||
      response.data?.result?.response ||
      "No response generated by the AI model.";

    return generatedText.trim();
  } catch (error) {
    console.error("❌ Huawei AI Service Error:");

    if (error.response) {
      console.error("Status:", error.response.status);
      console.error("Headers:", error.response.headers);
      console.error("Data:", JSON.stringify(error.response.data, null, 2));

      if (error.response.data?.error?.code === 'PANGU.3254') {
        console.error("💡 Solution: The model may not be available in your region or may require specific activation.");
      }
    } else if (error.request) {
      console.error("No response received:", error.request);
    } else {
      console.error("Error message:", error.message);
    }

    throw new Error(`AI model request failed: ${error.message}`);
  }
}

// Test example - now with mobile-optimized responses
// (async () => {
//   try {
//     console.log("🤖 Testing DEKAI AI Service...");

//     const result = await chatbotResponse(
//       "My chickens are dying",
//       undefined, // use default system instructions
//       {
//         max_tokens: 150, // Reduced for shorter responses
//         temperature: 0.7,
//         top_p: 0.9
//       }
//     );

//     console.log("✅ Model Output:", result);
//   } catch (error) {
//     console.error("❌ Error in chatbot call:", error.message);
//   }
// })();